# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test-build CI

# å½“æœ‰æ–°pushæˆ–è€…præ—¶è¿è¡Œ
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # ä¸€é¡¹å«åšbuild-and-deployçš„ä»»åŠ¡
  build-and-deploy:
    # åœ¨æœ€æ–°ç‰ˆçš„Ubuntuç³»ç»Ÿä¸‹è¿è¡Œ
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2 # æ¥è‡ªå®˜æ–¹è„šæœ¬ï¼šhttps://github.com/marketplace/actions/checkout

      - name: Install and Build
        run: |
          npm install
          npm run build
